/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Subtitle = string;
/**
 * The label for the value.
 */
export type Label = string;
/**
 * The unit of the value. e.g. °C or km/h
 */
export type Unit = string;
export type LabelColor = string;
export type ValueColor = string;
/**
 * Calculate the average over the given number of newest values. (If pivoted, then per each of the pivot dataseries.) If not specified then the latest value is shown without modification.
 */
export type AverageLatestValues = number;
export type Value = number;
/**
 * You can specify a column in the input data to autogenerate dataseries for each distinct entry in this column. E.g. if you have a table with columns [city, timestamp, temperature] and specify 'city' as pivot column, then you will get a gauge for each city.
 */
export type PivotColumn = string;
/**
 * The data used to draw this data series.
 */
export type Data = {
  value: Value;
  pivot?: PivotColumn;
  [k: string]: unknown;
}[];
export type ValueDisplays = {
  label: Label;
  unit?: Unit;
  labelColor?: LabelColor;
  valueColor?: ValueColor;
  averageLatest?: AverageLatestValues;
  data?: Data;
  [k: string]: unknown;
}[];

export interface ValueChartConfiguration {
  settings?: GlobalSettings;
  dataseries?: ValueDisplays;
  [k: string]: unknown;
}
export interface GlobalSettings {
  title?: Title;
  subTitle?: Subtitle;
  [k: string]: unknown;
}
